### PR TITLE
Fix AuthCredentials equality

### LINKED ISSUE #873: Caching authenticated users broken with anonymous auth
The backend registry tries to cache the authenticated `User` based on the `AuthCredentials`. When using the `HTTPClientCertAuthenticator`, the `AuthCredentials.password` is null. This causes the equality check to fail for equal `AuthCredentials.equals` even though it should not, because the function returns false if the object has a null password field: https://github.com/opendistro-for-elasticsearch/security/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/security/user/AuthCredentials.java#L183.

This results in _many_ calls to our authentication backend, which is unfortunately a blocking call to LDAP and synchronized on the cache.

### PR DESCRIPTION
**Pull request by nicot**
Fixes #873.

Description of changes:
This PR fixes the `AuthCredentials` class to correctly consider two `AuthCredentials` equal if they have the same username and both instances have null passwords. Before this PR, if both instances had null passwords, they would be considered not equal, causing them to never be cached. This fixes caching for backends using anonymous authentication.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by hardik-k-shah** [comment]
@nicot  Thanks for your contribution. Can you please verify why CI/CD is failing and fix tests if needed?

**Comment by nicot** [comment]
I've updated the tests to reflect the updated logic. This new caching seems to respect the comments on AuthenticationBackend better. I _think_ that the new counts in the test are correct, and the old ones were a workaround, but I'm not sure, so it would be great to confirm my understanding here.

File: src/main/java/com/amazon/opendistroforelasticsearch/security/user/AuthCredentials.java [hunk 1]
```diff
@@ -175,19 +176,16 @@ public int hashCode() {
...
-            if (other.username != null)
-                return false;
-        } else if (!username.equals(other.username))
-            return false;
-        return true;
+        return Objects.equals(username, other.username)
+            && Objects.equals(nativeCredentials, other.nativeCredentials)
+            && Objects.equals(backendRoles, other.backendRoles)
+            && MessageDigest.isEqual(internalPasswordHash, other.internalPasswordHash)
+            && Objects.equals(attributes, other.attributes);
```
Comment (cliu123) [inline src/main/java/com/amazon/opendistroforelasticsearch/security/user/AuthCredentials.java:188]: Add `&& Objects.equals(password, other.password)` here?

File: src/test/java/com/amazon/opendistroforelasticsearch/security/user/AuthCredentialsTests.java [hunk 2]
```diff
@@ -0,0 +1,19 @@
+package com.amazon.opendistroforelasticsearch.security.user;
+
+import org.junit.Assert;
+import org.junit.Test;
+
+public class AuthCredentialsTests {
+  @Test
+  public void testEquality() {
```
Comment (cliu123) [inline src/test/java/com/amazon/opendistroforelasticsearch/security/user/AuthCredentialsTests.java:8]: Should we add 2 test cases?
1. `object.internalPasswordHash == null` && `other. internalPasswordHash == null` ==> equals() returns true
2. `object.internalPasswordHash == null` && `other. internalPasswordHash == <anything other than null>` returns false.

File: src/test/java/com/amazon/opendistroforelasticsearch/security/cache/CachingTest.java [hunk 3]
```diff
@@ -58,7 +58,7 @@ public void testRestCaching() throws Exception {
 
         Assert.assertEquals(3, DummyHTTPAuthenticator.getCount());
         Assert.assertEquals(1, DummyAuthorizer.getCount());
-        Assert.assertEquals(3, DummyAuthenticationBackend.getAuthCount());
+        Assert.assertEquals(1, DummyAuthenticationBackend.getAuthCount());
```
Comment (cliu123) [inline src/test/java/com/amazon/opendistroforelasticsearch/security/cache/CachingTest.java:61]: Why is this change necessary? It doesn't look related to your change.

File: src/test/java/com/amazon/opendistroforelasticsearch/security/cache/CachingTest.java [hunk 4]
```diff
@@ -103,7 +103,7 @@ public void testRestCachingWithImpersonation() throws Exception {
 
         Assert.assertEquals(4, DummyHTTPAuthenticator.getCount());
         Assert.assertEquals(3, DummyAuthorizer.getCount());
-        Assert.assertEquals(4, DummyAuthenticationBackend.getAuthCount());
+        Assert.assertEquals(1, DummyAuthenticationBackend.getAuthCount());
```
Comment (cliu123) [inline src/test/java/com/amazon/opendistroforelasticsearch/security/cache/CachingTest.java:106]: Why is this change necessary? It doesn't look related to your change.

File: src/test/java/com/amazon/opendistroforelasticsearch/security/cache/CachingTest.java (hunk 3 above)
Comment (nicot) [reply src/test/java/com/amazon/opendistroforelasticsearch/security/cache/CachingTest.java:61]: My change fixes caching auth credentials, so the authentication backend is hit less. That's how I found this bug in the first place.

File: src/test/java/com/amazon/opendistroforelasticsearch/security/cache/CachingTest.java (hunk 4 above)
Comment (nicot) [reply src/test/java/com/amazon/opendistroforelasticsearch/security/cache/CachingTest.java:106]: Same here, caching auth credentials was broken before because equality wasn't working on the key. Now that it is fixed the calls to the authentication backend are properly cached and the backend is hit less.

File: src/main/java/com/amazon/opendistroforelasticsearch/security/user/AuthCredentials.java (hunk 1 above)
Comment (nicot) [reply src/main/java/com/amazon/opendistroforelasticsearch/security/user/AuthCredentials.java:188]: The password is always filled with nulls and then set to null in the constructor, and the internalPasswordHash is used instead. We can check it here though if you prefer.

Comment (cliu123) [reply src/main/java/com/amazon/opendistroforelasticsearch/security/user/AuthCredentials.java:188]: Is it possible to be non-null values in any scenarios? If so, I'd add a check for it.

Comment (nicot) [reply src/main/java/com/amazon/opendistroforelasticsearch/security/user/AuthCredentials.java:188]: It is not possible, but I can still add the check, is that what you'd prefer?

Comment (cliu123) [reply src/main/java/com/amazon/opendistroforelasticsearch/security/user/AuthCredentials.java:188]: Yes, let's add the check. Thanks!

**Comment by cliu123** [comment]
Meanwhile, could you kindly rebase/squash your commits and only keep a single commit with the message same as your PR title? That would help us generate release notes up releases. Thanks!

**Review by cliu123 — APPROVED** [review]

**Comment by cliu123** [comment]
@nicot  Thanks for contributing!

File: src/test/java/com/amazon/opendistroforelasticsearch/security/user/AuthCredentialsTests.java (hunk 2 above)
Comment (cliu123) [reply src/test/java/com/amazon/opendistroforelasticsearch/security/user/AuthCredentialsTests.java:8]: @nicot Can you add these 2 test cases?

Comment (nicot) [reply src/test/java/com/amazon/opendistroforelasticsearch/security/user/AuthCredentialsTests.java:8]: A user password will be null if we set the `backendRoles`.

> object.internalPasswordHash == null && other.internalPasswordHash == null ==> equals() returns true

This is the test case on line 9 — the users have backendRoles, so the password is null for both.


> object.internalPasswordHash == null && other.internalPasswordHash == <non-null value> ==> equals() returns false.

This is the test case on line 28 — one user has backendRoles and one has a password, and they are not equal.

**Review by palashhedau — APPROVED** [review]
